# CONSTANTS
LINESIZE = 32
NUM_FIRST_CLUSTER = 2
NUM_CLUSTERS = 8
NUM_TYPES = NUM_CLUSTERS - NUM_FIRST_CLUSTER - 1

DTYPE_SIZE = 8                  # [bit] uint8_t
DTYPE_RANGE = 2 ** DTYPE_SIZE
MIN_VAL = 1e-9

SCANNED_SYMBOL_SIZE = 16

